# Generated by Django 3.2.3 on 2021-05-25 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rotation_cycle_length', models.IntegerField(default=80)),
                ('forced_rotation_temp', models.IntegerField(default=0)),
                ('night_length', models.IntegerField(default=480)),
                ('max_intake_time', models.IntegerField(default=5)),
                ('max_exhaust_time', models.IntegerField(default=5)),
                ('winter_rotation_count', models.IntegerField(default=45)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djmq.user')),
            ],
        ),
    ]
