# Generated by Django 3.2.3 on 2021-05-26 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djmq', '0003_alter_device_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='modification',
            field=models.IntegerField(default=0),
        ),
    ]
